config/routes.rb
Rails.application.routes.draw do
  resources :charts

  root 'charts#index'

end

app/models/chart.rb
class Chart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  include ChartUtils
  helper_method :color_set
  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
    json_file = Dir["app/assets/jsons/*.json"]

    data = []
    date_hash = []

    # binding.pry
    json_file.each_with_index do |json, i|
      _parsed_file = JSON.parse(File.read(json))
      word_counts = _parsed_file.sort_by{ |k,v| k }.last(100).to_h
      date_hash << word_counts.keys

      line_data = Hash.new
      line_data[:label] = json.gsub('_parsed.json', '').gsub('app/assets/jsons/', '') # 檔名
      line_data[:backgroundColor] = "rgba(0,0,0,0)"
      line_data[:pointBackgroundColor] = color_set(alpha: 1)[i]
      line_data[:borderColor] = color_set(alpha: 1)[i]
      line_data[:pointBorderColor] = "#fff"
      line_data[:pointHighlightFill] = "#fff"
      line_data[:highlightBackgroundColor] = color_set(alpha: 0.2)[i]
      line_data[:pointHighlightStroke] = color_set(alpha: 1)[i]
      line_data[:hoverBackgroundColor] = color_set(alpha: 0.2)[i]
      line_data[:borderWidth] = 2
      line_data[:data] = word_counts.values
      # binding.pry
      # binding.pry
      data.push(line_data)
    end

    # binding.pry

    @data = {
      labels: date_hash.flatten.uniq,
      datasets: data
    }
      # binding.pry

    @options = {
      responsive: true,
      height: 240,
      legend: {
        display: true,
        width: 20
      }
    }
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
    filename = params[:id]
    json_file = Dir["app/assets/jsons/#{filename}_parsed.json"][0]
    parsed_file = JSON.parse(File.read(json_file))
    date_hash = parsed_file.keys.sort
    word_counts = parsed_file.sort_by{ |k,v| k }.to_h

    # binding.pry

    @data = {
      labels: word_counts.keys,
      datasets: [
        {
          label: filename,
          backgroundColor: "rgba(220,220,220,0.2)",
          borderColor: "rgba(220,220,220,1)",
          data: word_counts.values
        }
      ]
    }

    @options = {
      responsive: true,
      height: 240,
      legend: {
        display: true,
        width: 20
      }
    }
  end

end

app/controllers/concerns/chart_utils.rb
module ChartUtils
  def color_set(alpha: 1)
    [ "rgba(241,44,81,#{alpha})", "rgba(0,160,233,#{alpha})", "rgba(243,194,24,#{alpha})",
      "rgba(143,195,31,#{alpha})", "rgba(235,104,119,#{alpha})", "rgba(126,206,244,#{alpha})",
      "rgba(255,229,53,#{alpha})", "rgba(137,201,151,#{alpha})", "rgba(236,105,65,#{alpha})",
      "rgba(0,160,233,#{alpha})", "rgba(68,138,202,#{alpha})", "rgba(248,181,81,#{alpha})",
      "rgba(19,181,277,#{alpha})", "rgba(150,150,150,#{alpha})" ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<%= image_tag "1.jpg" %>
<%= image_tag "2.svg" %>
<%= image_tag "3.svg" %>
<%= image_tag "4.svg" %>
<%= image_tag "5.svg" %>
<%= image_tag "6.svg" %>

<%= line_chart @data, @options %>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<!-- <p id="notice"><%#= notice %></p> -->

<%= line_chart           @data, @options %>

<%#= link_to 'Edit', edit_chart_path(@chart) %> |
<%#= link_to 'Back', charts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PttTextMining</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>